[package]
name = "deep"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", features = ["wayland"] }
bevy_atmosphere = "*"
bevy_editor_pls = "*"
bevy_rapier3d = "*"
colorgrad = "*"
image = "*"
nalgebra = "*"
rand = "*"
uuid = "*"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
